[profile.default]
  auto-detect-solc = true
  evm_version = "cancun"
  fs_permissions = [
    { access = "write", path = "./test/gas-reports/lst-gas-report.json" },
  ]
  ignored_warnings_from = ["src/interfaces/IWETH9.sol"]
  optimizer = true
  optimizer_runs = 200
  remappings = [
    "lib/staker:src=lib/staker/src/",
    "@staker/=lib/staker/",
    "forge-std/=lib/forge-std/src",
    "openzeppelin/=lib/openzeppelin-contracts/contracts",
  ]
  verbosity = 3
  via-ir = false

[profile.ci]
  fuzz = { runs = 3000 }
  invariant = { runs = 1000 }

[profile.coverage]
  fuzz = { runs = 100 }
  invariant = { runs = 0 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[invariant]
  call_override = false
  depth = 100
  dictionary_weight = 80
  fail_on_revert = false
  include_push_bytes = true
  include_storage = true
  optimizer = false
  runs = 25

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 2
  wrap_comments = true

[fuzz]
  # We turn on this setting to prevent the fuzzer from picking DelegationSurrogate contracts,
  # including before they're actually even deployed, as some other entity in the test, for example
  # depositor. This makes no sense and breaks test assertions, but is extremely difficult to handle
  # with assume statements because we don't have the surrogate address until it's deployed later in
  # the test.
  include_storage = false
  #include_push_bytes = false
